//! Trade impulse detector for microstructure alpha.
//!
//! Detects fast price moves on one exchange while the other lags.
//! Pure event-driven signal - no correlation needed.
//!
//! # Algorithm
//! 1. Track midprice changes on both exchanges (exchange timestamps for delta)
//! 2. Use LOCAL receive timestamps for freshness gating (exchange clocks are unreliable)
//! 3. Detect when one exchange moves > threshold_bps
//! 4. Check if other exchange hasn't reacted (< lag_threshold_bps)
//! 5. Generate signal to trade the laggard

use crate::eal::{OrderSide, Symbol, Tick, VenueId};

fn now_ns() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos() as u64
}

/// Midprice tracker for impulse detection
///
/// Tracks price changes over a sliding window to detect fast moves.
/// All operations are O(1) with no heap allocation.
struct MidpriceTracker {
    /// Current midprice (from last tick)
    current_mid: Option<f64>,
    /// Midprice from N ms ago
    prev_mid: Option<f64>,
    /// Timestamp of prev_mid update (exchange timestamp, for delta calc)
    prev_timestamp_ns: u64,
    /// Window size in nanoseconds
    window_ns: u64,
    /// Whether the tracker has received at least one tick
    initialized: bool,
    /// Whether the tracker has completed one full window cycle (warmup)
    warmed_up: bool,
    /// LOCAL receive timestamp of last tick (for freshness gating)
    last_local_update_ns: u64,
}

impl MidpriceTracker {
    #[inline(always)]
    fn new(window_ns: u64) -> Self {
        Self {
            current_mid: None,
            prev_mid: None,
            prev_timestamp_ns: 0,
            window_ns,
            initialized: false,
            warmed_up: false,
            last_local_update_ns: 0,
        }
    }

    /// Update with new tick, returns delta if window elapsed.
    /// Delta uses exchange timestamps (consistent within venue).
    /// Local timestamp updated for freshness gating.
    #[inline(always)]
    fn update(&mut self, tick: &Tick) -> Option<f64> {
        let current_ns = tick.exchange_ts_ns;
        let price = tick.price;

        if !price.is_finite() || price <= 0.0 {
            return None;
        }

        // Always update local receive time for freshness gating
        self.last_local_update_ns = now_ns();
        self.current_mid = Some(price);

        if let Some(prev) = self.prev_mid {
            if prev > 0.0
                && prev.is_finite()
                && current_ns >= self.prev_timestamp_ns
                && current_ns - self.prev_timestamp_ns >= self.window_ns
            {
                let delta = (price - prev) / prev * 10000.0;
                self.prev_mid = Some(price);
                self.prev_timestamp_ns = current_ns;

                if !self.warmed_up {
                    self.warmed_up = true;
                    return None;
                }

                return if delta.is_finite() { Some(delta) } else { None };
            }
        } else {
            self.prev_mid = Some(price);
            self.prev_timestamp_ns = current_ns;
            self.initialized = true;
        }

        None
    }

    #[inline(always)]
    fn current_mid(&self) -> Option<f64> {
        self.current_mid
    }

    #[inline(always)]
    fn current_delta(&self) -> Option<f64> {
        match (self.current_mid, self.prev_mid) {
            (Some(current), Some(prev))
                if prev > 0.0 && prev.is_finite() && current.is_finite() =>
            {
                Some((current - prev) / prev * 10000.0)
            }
            _ => None,
        }
    }
}

/// Impulse signal generated by trade impulse detector
#[derive(Debug, Clone)]
pub struct ImpulseSignal {
    pub side: OrderSide,
    pub target_venue: VenueId,
    pub symbol: Symbol,
    pub impulse_magnitude_bps: f64,
    pub timestamp_ns: u64,
}

/// Trade impulse detector
pub struct ImpulseDetector {
    tracker_a: MidpriceTracker,
    tracker_b: MidpriceTracker,
    impulse_threshold_bps: f64,
    lag_threshold_bps: f64,
    min_trade_size: f64,
    signal_timeout_ns: u64,
    /// Freshness gate: both venues must have received a tick within this window (LOCAL time)
    venue_freshness_ns: u64,
}

impl ImpulseDetector {
    pub fn new(
        window_ns: u64,
        impulse_threshold_bps: f64,
        lag_threshold_bps: f64,
        min_trade_size: f64,
        signal_timeout_ns: u64,
        venue_freshness_ns: u64,
    ) -> Self {
        Self {
            tracker_a: MidpriceTracker::new(window_ns),
            tracker_b: MidpriceTracker::new(window_ns),
            impulse_threshold_bps,
            lag_threshold_bps,
            min_trade_size,
            signal_timeout_ns,
            venue_freshness_ns,
        }
    }

    /// Process tick and detect impulse.
    ///
    /// Returns signal if all gates pass:
    /// 1. Trade size >= min_trade_size
    /// 2. Both trackers initialized AND warmed up
    /// 3. Both venues fresh (local receive time within venue_freshness_ns)
    /// 4. Delta > threshold AND < 500 bps sanity
    /// 5. Other venue lagging (delta < lag_threshold_bps)
    pub fn process_tick(&mut self, tick: &Tick) -> Option<ImpulseSignal> {
        if tick.size < self.min_trade_size {
            return None;
        }

        let venue = tick.venue;
        let symbol = tick.symbol.clone();
        let timestamp_ns = now_ns();

        // Route tick to correct tracker
        let delta = match venue {
            VenueId::EXCHANGE_A => self.tracker_a.update(tick),
            VenueId::EXCHANGE_B => self.tracker_b.update(tick),
            _ => return None,
        };

        // Both trackers must be initialized AND warmed up
        if !self.tracker_a.initialized
            || !self.tracker_b.initialized
            || !self.tracker_a.warmed_up
            || !self.tracker_b.warmed_up
        {
            return None;
        }

        // Freshness gate: both venues must have ticked recently (LOCAL timestamps)
        let a_stale = timestamp_ns.saturating_sub(self.tracker_a.last_local_update_ns)
            > self.venue_freshness_ns;
        let b_stale = timestamp_ns.saturating_sub(self.tracker_b.last_local_update_ns)
            > self.venue_freshness_ns;
        if a_stale || b_stale {
            return None;
        }

        if let Some(delta_bps) = delta {
            // Sanity check + threshold
            if delta_bps.is_finite()
                && delta_bps.abs() > self.impulse_threshold_bps
                && delta_bps.abs() < 500.0
            {
                let other_delta = match venue {
                    VenueId::EXCHANGE_A => self.tracker_b.current_delta(),
                    VenueId::EXCHANGE_B => self.tracker_a.current_delta(),
                    _ => return None,
                };

                tracing::info!(
                    "Impulse detected on {:?}: {} | delta={:.4} bps | threshold={:.1} bps",
                    venue,
                    symbol,
                    delta_bps,
                    self.impulse_threshold_bps
                );

                // Lag check: other venue must have a delta AND it must be small
                let other_is_lagging = match other_delta {
                    Some(d) => d.is_finite() && d.abs() < self.lag_threshold_bps,
                    None => false,
                };

                if other_is_lagging {
                    let side = if delta_bps > 0.0 {
                        OrderSide::Buy
                    } else {
                        OrderSide::Sell
                    };
                    let target_venue = match venue {
                        VenueId::EXCHANGE_A => VenueId::EXCHANGE_B,
                        _ => VenueId::EXCHANGE_A,
                    };
                    return Some(ImpulseSignal {
                        side,
                        target_venue,
                        symbol,
                        impulse_magnitude_bps: delta_bps,
                        timestamp_ns,
                    });
                }
            }
        }

        None
    }

    pub fn is_signal_expired(&self, current_ns: u64) -> bool {
        false // timeout handled at OMS level
    }

    pub fn current_mid(&self, venue: VenueId) -> Option<f64> {
        match venue {
            VenueId::EXCHANGE_A => self.tracker_a.current_mid(),
            VenueId::EXCHANGE_B => self.tracker_b.current_mid(),
            _ => None,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eal::Symbol;

    fn make_tick(venue: VenueId, price: f64, size: f64, ts_ns: u64) -> Tick {
        Tick {
            venue,
            symbol: Symbol::new("BTC"),
            price,
            size,
            exchange_ts_ns: ts_ns,
            local_ts_ns: ts_ns,
        }
    }

    #[test]
    fn test_midprice_tracker_basic() {
        let mut tracker = MidpriceTracker::new(5_000_000);

        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 0));
        assert!(delta.is_none());
        assert!(tracker.initialized);

        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.1, 1.0, 2_000_000));
        assert!(delta.is_none());

        // Warmup delta (skipped)
        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.5, 1.0, 6_000_000));
        assert!(delta.is_none(), "First delta should be warmup");
        assert!(tracker.warmed_up);

        // Real delta
        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.6, 1.0, 12_000_000));
        assert!(delta.is_some());
        assert!((delta.unwrap() - 9.95).abs() < 1.0);
    }

    #[test]
    fn test_impulse_detector_basic() {
        let mut detector = ImpulseDetector::new(
            5_000_000,
            5.0,
            1.5,
            0.001,
            10_000_000,
            400_000_000, // 400ms freshness
        );

        // Init both trackers
        detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 0));
        detector.process_tick(&make_tick(VenueId::EXCHANGE_B, 100.0, 1.0, 0));

        // Warmup
        detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 6_000_000));
        detector.process_tick(&make_tick(VenueId::EXCHANGE_B, 100.0, 1.0, 6_000_000));

        // A moves 10bps, B flat
        let signal = detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.1, 1.0, 12_000_000));
        assert!(
            signal.is_some(),
            "Impulse should fire: A moved 10bps, B flat"
        );
        let sig = signal.unwrap();
        assert_eq!(sig.side, OrderSide::Buy);
        assert_eq!(sig.target_venue, VenueId::EXCHANGE_B);
    }

    #[test]
    fn test_freshness_gate_rejects_stale() {
        let mut detector =
            ImpulseDetector::new(5_000_000, 5.0, 1.5, 0.001, 10_000_000, 400_000_000);

        // Init and warmup A only
        detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 0));
        detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 6_000_000));

        // B not initialized — no impulse
        let signal = detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.5, 1.0, 12_000_000));
        assert!(signal.is_none(), "No impulse: B not initialized");
    }

    #[test]
    fn test_impulse_detector_filters_small_trades() {
        let mut detector =
            ImpulseDetector::new(5_000_000, 5.0, 1.5, 0.001, 10_000_000, 400_000_000);
        let signal = detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.1, 0.0001, 0));
        assert!(signal.is_none());
    }

    #[test]
    fn test_local_timestamp_tracking() {
        let mut tracker = MidpriceTracker::new(5_000_000);
        assert_eq!(tracker.last_local_update_ns, 0);

        tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 0));
        assert!(
            tracker.last_local_update_ns > 0,
            "Local timestamp should be set"
        );
    }
}
