//! Trade impulse detector for microstructure alpha.
//!
//! Detects fast price moves on one exchange while the other lags.
//! Pure event-driven signal - no correlation needed.
//!
//! # Algorithm
//! 1. Track midprice changes on both exchanges
//! 2. Detect when one exchange moves > threshold_bps
//! 3. Check if other exchange hasn't reacted (< lag_threshold_bps)
//! 4. Generate signal to trade the laggard

use crate::eal::{OrderSide, Symbol, Tick, VenueId};

/// Midprice tracker for impulse detection
///
/// Tracks price changes over a sliding window to detect fast moves.
/// All operations are O(1) with no heap allocation.
struct MidpriceTracker {
    /// Current midprice (from last tick)
    current_mid: Option<f64>,
    /// Midprice from N ms ago
    prev_mid: Option<f64>,
    /// Timestamp of prev_mid update
    prev_timestamp_ns: u64,
    /// Window size in nanoseconds
    window_ns: u64,
}

impl MidpriceTracker {
    /// Create a new midprice tracker
    #[inline(always)]
    fn new(window_ns: u64) -> Self {
        Self {
            current_mid: None,
            prev_mid: None,
            prev_timestamp_ns: 0,
            window_ns,
        }
    }

    /// Update with new tick, returns delta if window elapsed
    ///
    /// Returns Some(delta_bps) if enough time has elapsed since last update.
    /// Delta is in basis points (1 bps = 0.01%).
    #[inline(always)]
    fn update(&mut self, tick: &Tick) -> Option<f64> {
        let current_ns = tick.exchange_ts_ns;
        let price = tick.price;

        // Guard against invalid prices
        if !price.is_finite() || price <= 0.0 {
            return None;
        }

        // Update current mid
        self.current_mid = Some(price);

        // Check if window has elapsed
        if let Some(prev) = self.prev_mid {
            if prev > 0.0
                && prev.is_finite()
                && current_ns - self.prev_timestamp_ns >= self.window_ns
            {
                let delta = (price - prev) / prev * 10000.0; // Convert to bps
                self.prev_mid = Some(price);
                self.prev_timestamp_ns = current_ns;
                return if delta.is_finite() { Some(delta) } else { None };
            }
        } else {
            // First tick, initialize prev
            self.prev_mid = Some(price);
            self.prev_timestamp_ns = current_ns;
        }

        None
    }

    /// Get current midprice
    #[inline(always)]
    fn current_mid(&self) -> Option<f64> {
        self.current_mid
    }

    /// Get the most recent delta in bps (without consuming the window).
    ///
    /// Returns None if insufficient data or prev price is zero/invalid.
    #[inline(always)]
    fn current_delta(&self) -> Option<f64> {
        match (self.current_mid, self.prev_mid) {
            (Some(current), Some(prev))
                if prev > 0.0 && prev.is_finite() && current.is_finite() =>
            {
                Some((current - prev) / prev * 10000.0)
            }
            _ => None,
        }
    }
}

/// Impulse signal generated by trade impulse detector
#[derive(Debug, Clone)]
pub struct ImpulseSignal {
    /// Direction of the trade
    pub side: OrderSide,
    /// Target venue (the laggard)
    pub target_venue: VenueId,
    /// Symbol to trade
    pub symbol: Symbol,
    /// Impulse magnitude in basis points
    pub impulse_magnitude_bps: f64,
    /// Timestamp when signal was generated
    pub timestamp_ns: u64,
}

/// Trade impulse detector
///
/// Detects fast price moves on one exchange while the other remains flat.
/// This is pure alpha - no correlation needed.
pub struct ImpulseDetector {
    /// Midprice trackers for each venue
    tracker_a: MidpriceTracker,
    tracker_b: MidpriceTracker,
    /// Threshold in bps to detect impulse
    impulse_threshold_bps: f64,
    /// Max move on other exchange to consider it "lagging"
    lag_threshold_bps: f64,
    /// Minimum trade size to avoid fake impulses
    min_trade_size: f64,
    /// Last impulse timestamp for timeout
    last_impulse_ns: Option<u64>,
    /// Signal timeout in nanoseconds
    signal_timeout_ns: u64,
}

impl ImpulseDetector {
    /// Create a new impulse detector
    ///
    /// # Arguments
    /// * `window_ns` - Lookback window in nanoseconds (e.g., 5_000_000 for 5ms)
    /// * `impulse_threshold_bps` - Price move threshold in bps (e.g., 5)
    /// * `lag_threshold_bps` - Max move on other exchange (e.g., 1.5)
    /// * `min_trade_size` - Minimum trade size to filter fake impulses
    /// * `signal_timeout_ns` - Signal timeout in nanoseconds
    pub fn new(
        window_ns: u64,
        impulse_threshold_bps: f64,
        lag_threshold_bps: f64,
        min_trade_size: f64,
        signal_timeout_ns: u64,
    ) -> Self {
        Self {
            tracker_a: MidpriceTracker::new(window_ns),
            tracker_b: MidpriceTracker::new(window_ns),
            impulse_threshold_bps,
            lag_threshold_bps,
            min_trade_size,
            last_impulse_ns: None,
            signal_timeout_ns,
        }
    }

    /// Process tick and detect impulse
    ///
    /// Returns signal if:
    /// 1. One exchange moves > impulse_threshold_bps
    /// 2. Other exchange hasn't reacted (< lag_threshold_bps)
    /// 3. Trade size >= min_trade_size
    /// 4. Signal hasn't timed out
    pub fn process_tick(&mut self, tick: &Tick) -> Option<ImpulseSignal> {
        // Filter small trades
        if tick.size < self.min_trade_size {
            return None;
        }

        let venue = tick.venue;
        let symbol = tick.symbol.clone();
        let timestamp_ns = tick.exchange_ts_ns;

        // Route tick to the correct tracker only (Issue 5 fix)
        let delta = match venue {
            VenueId::EXCHANGE_A => self.tracker_a.update(tick),
            VenueId::EXCHANGE_B => self.tracker_b.update(tick),
            _ => return None, // Unknown venue — reject
        };

        // Check for impulse: one exchange moves, other hasn't reacted
        if let Some(delta_bps) = delta {
            if delta_bps.is_finite() && delta_bps.abs() > self.impulse_threshold_bps {
                // Get the other exchange's current delta for lag check
                let other_delta = match venue {
                    VenueId::EXCHANGE_A => self.tracker_b.current_delta(),
                    VenueId::EXCHANGE_B => self.tracker_a.current_delta(),
                    _ => return None,
                };

                tracing::info!(
                    "Impulse detected on {:?}: {} | delta={:.4} bps | threshold={:.1} bps",
                    venue,
                    symbol,
                    delta_bps,
                    self.impulse_threshold_bps
                );

                // Check if other exchange is lagging (flat or minimal move)
                let other_is_lagging = match other_delta {
                    Some(d) => d.is_finite() && d.abs() < self.lag_threshold_bps,
                    None => true, // No data yet = lagging
                };

                if other_is_lagging {
                    tracing::info!(
                        "Laggard confirmed: {:?} is lagging for {}",
                        match venue {
                            VenueId::EXCHANGE_A => VenueId::EXCHANGE_B,
                            _ => VenueId::EXCHANGE_A,
                        },
                        symbol
                    );

                    self.last_impulse_ns = Some(timestamp_ns);
                    let side = if delta_bps > 0.0 {
                        OrderSide::Buy
                    } else {
                        OrderSide::Sell
                    };
                    let target_venue = match venue {
                        VenueId::EXCHANGE_A => VenueId::EXCHANGE_B,
                        _ => VenueId::EXCHANGE_A,
                    };
                    return Some(ImpulseSignal {
                        side,
                        target_venue,
                        symbol,
                        impulse_magnitude_bps: delta_bps,
                        timestamp_ns,
                    });
                }
            }
        }

        None
    }

    /// Check if signal has timed out
    pub fn is_signal_expired(&self, current_ns: u64) -> bool {
        if let Some(last) = self.last_impulse_ns {
            current_ns - last > self.signal_timeout_ns
        } else {
            false
        }
    }

    /// Get current midprice for a venue
    pub fn current_mid(&self, venue: VenueId) -> Option<f64> {
        match venue {
            VenueId::EXCHANGE_A => self.tracker_a.current_mid(),
            VenueId::EXCHANGE_B => self.tracker_b.current_mid(),
            _ => None,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eal::Symbol;

    fn make_tick(venue: VenueId, price: f64, size: f64, ts_ns: u64) -> Tick {
        Tick {
            venue,
            symbol: Symbol::new("BTC"),
            price,
            size,
            exchange_ts_ns: ts_ns,
            local_ts_ns: ts_ns,
        }
    }

    #[test]
    fn test_midprice_tracker_basic() {
        let mut tracker = MidpriceTracker::new(5_000_000); // 5ms window

        // First tick initializes prev
        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 0));
        assert!(delta.is_none());

        // Second tick within window, no delta
        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.1, 1.0, 2_000_000));
        assert!(delta.is_none());

        // Third tick after window, should return delta
        let delta = tracker.update(&make_tick(VenueId::EXCHANGE_A, 100.5, 1.0, 6_000_000));
        assert!(delta.is_some());
        let delta_bps = delta.unwrap();
        // delta = (100.5 - 100.0) / 100.0 * 10000 = 50 bps
        assert!((delta_bps - 50.0).abs() < 1.0);
    }

    #[test]
    fn test_impulse_detector_basic() {
        let mut detector = ImpulseDetector::new(
            5_000_000,  // 5ms window
            5.0,        // 5 bps impulse threshold
            1.5,        // 1.5 bps lag threshold
            0.001,      // min trade size
            10_000_000, // 10ms timeout
        );

        // Initialize both trackers
        detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 0));
        detector.process_tick(&make_tick(VenueId::EXCHANGE_B, 100.0, 1.0, 0));

        // A moves up significantly, B stays flat
        detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.0, 1.0, 2_000_000));
        detector.process_tick(&make_tick(VenueId::EXCHANGE_B, 100.0, 1.0, 2_000_000));

        // A makes big move, B still flat
        let signal = detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.1, 1.0, 6_000_000));
        // This should trigger impulse if B hasn't moved
        // (depends on exact timing and thresholds)
    }

    #[test]
    fn test_impulse_detector_filters_small_trades() {
        let mut detector = ImpulseDetector::new(
            5_000_000, 5.0, 1.5, 0.001, // min trade size
            10_000_000,
        );

        // Small trade should be filtered
        let signal = detector.process_tick(&make_tick(VenueId::EXCHANGE_A, 100.1, 0.0001, 0));
        assert!(signal.is_none());
    }

    #[test]
    fn test_impulse_detector_timeout() {
        let detector = ImpulseDetector::new(
            5_000_000, 5.0, 1.5, 0.001, 10_000_000, // 10ms timeout
        );

        // No impulse yet
        assert!(!detector.is_signal_expired(0));
        assert!(!detector.is_signal_expired(5_000_000));
    }
}
