//! OBI divergence detector for order book alpha.
//!
//! Detects when one exchange shows strong bid/ask pressure
//! while the other remains neutral.
//!
//! # Algorithm
//! 1. Calculate depth-weighted OBI for both exchanges
//! 2. Track persistence (OBI must stay strong for N ms)
//! 3. Detect when one exchange has strong imbalance (> threshold)
//! 4. Check if other exchange is neutral (< neutral_threshold)
//! 5. Generate signal to trade the neutral exchange

use crate::eal::{BookUpdate, OrderSide, Symbol, VenueId};

fn now_ns() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos() as u64
}

/// OBI signal generated by divergence detector
#[derive(Debug, Clone)]
pub struct ObiSignal {
    pub side: OrderSide,
    pub target_venue: VenueId,
    pub symbol: Symbol,
    pub obi_value: f64,
    pub obi_delta: Option<f64>,
    pub timestamp_ns: u64,
}

/// OBI divergence detector
pub struct ObiDivergenceDetector {
    strong_threshold: f64,
    neutral_threshold: f64,
    depth: usize,
    current_obi_a: Option<f64>,
    current_obi_b: Option<f64>,
    prev_obi_a: Option<f64>,
    spike_threshold: f64,
    /// Time-based persistence: timestamp when OBI first went strong (per venue)
    persist_start_a: Option<u64>,
    persist_start_b: Option<u64>,
    /// OBI must stay strong for this long (nanoseconds)
    obi_persist_ns: u64,
}

impl ObiDivergenceDetector {
    pub fn new(
        strong_threshold: f64,
        neutral_threshold: f64,
        depth: usize,
        spike_threshold: f64,
        obi_persist_ns: u64,
    ) -> Self {
        Self {
            strong_threshold,
            neutral_threshold,
            depth,
            current_obi_a: None,
            current_obi_b: None,
            prev_obi_a: None,
            spike_threshold,
            persist_start_a: None,
            persist_start_b: None,
            obi_persist_ns,
        }
    }

    /// Depth-weighted OBI: top levels matter more.
    /// Weight = 1/(i+1): level 0 = 1.0, level 1 = 0.5, level 2 = 0.33...
    fn weighted_obi(&self, book: &BookUpdate) -> f64 {
        let mut weighted_bid = 0.0;
        let mut weighted_ask = 0.0;

        for (i, level) in book.bids.iter().take(self.depth).enumerate() {
            weighted_bid += level.size / (i as f64 + 1.0);
        }
        for (i, level) in book.asks.iter().take(self.depth).enumerate() {
            weighted_ask += level.size / (i as f64 + 1.0);
        }

        let total = weighted_bid + weighted_ask;
        if total > 0.0 {
            (weighted_bid - weighted_ask) / total
        } else {
            0.0
        }
    }

    /// Process book update and detect divergence
    pub fn process_book(&mut self, book: &BookUpdate) -> Option<ObiSignal> {
        let venue = book.venue;
        let symbol = book.symbol.clone();
        let timestamp_ns = now_ns();

        let obi = self.weighted_obi(book);

        tracing::debug!(
            "OBI update: {} | venue={:?} | obi={:.4}",
            symbol,
            venue,
            obi
        );

        // Update current OBI and persistence tracking
        match venue {
            VenueId::EXCHANGE_A => {
                self.prev_obi_a = self.current_obi_a;
                self.current_obi_a = Some(obi);
                // Time-based persistence
                if obi.abs() > self.strong_threshold {
                    if self.persist_start_a.is_none() {
                        self.persist_start_a = Some(timestamp_ns);
                    }
                } else {
                    self.persist_start_a = None;
                }
            }
            VenueId::EXCHANGE_B => {
                self.current_obi_b = Some(obi);
                if obi.abs() > self.strong_threshold {
                    if self.persist_start_b.is_none() {
                        self.persist_start_b = Some(timestamp_ns);
                    }
                } else {
                    self.persist_start_b = None;
                }
            }
            _ => return None,
        }

        // OBI delta for liquidity shift detection
        let obi_delta = if venue == VenueId::EXCHANGE_A {
            if let (Some(prev), Some(current)) = (self.prev_obi_a, self.current_obi_a) {
                let delta = current - prev;
                if delta.abs() > self.spike_threshold {
                    tracing::info!("Liquidity shift: {} | delta_obi={:.4}", symbol, delta);
                }
                Some(delta)
            } else {
                None
            }
        } else {
            None
        };

        // Check for divergence (both venues must have OBI)
        if let (Some(obi_a), Some(obi_b)) = (self.current_obi_a, self.current_obi_b) {
            // Check persistence for venue A
            let a_persisted = match self.persist_start_a {
                Some(start) => timestamp_ns - start >= self.obi_persist_ns,
                None => false,
            };
            // Check persistence for venue B
            let b_persisted = match self.persist_start_b {
                Some(start) => timestamp_ns - start >= self.obi_persist_ns,
                None => false,
            };

            // A strong + persisted, B neutral → BUY on B
            if a_persisted && obi_a > self.strong_threshold && obi_b.abs() < self.neutral_threshold
            {
                return Some(ObiSignal {
                    side: OrderSide::Buy,
                    target_venue: VenueId::EXCHANGE_B,
                    symbol,
                    obi_value: obi_a,
                    obi_delta,
                    timestamp_ns,
                });
            }

            // A negative strong + persisted, B neutral → SELL on B
            if a_persisted && obi_a < -self.strong_threshold && obi_b.abs() < self.neutral_threshold
            {
                return Some(ObiSignal {
                    side: OrderSide::Sell,
                    target_venue: VenueId::EXCHANGE_B,
                    symbol,
                    obi_value: obi_a,
                    obi_delta,
                    timestamp_ns,
                });
            }

            // B strong + persisted, A neutral → BUY on A
            if b_persisted && obi_b > self.strong_threshold && obi_a.abs() < self.neutral_threshold
            {
                return Some(ObiSignal {
                    side: OrderSide::Buy,
                    target_venue: VenueId::EXCHANGE_A,
                    symbol,
                    obi_value: obi_b,
                    obi_delta: None,
                    timestamp_ns,
                });
            }

            // B negative strong + persisted, A neutral → SELL on A
            if b_persisted && obi_b < -self.strong_threshold && obi_a.abs() < self.neutral_threshold
            {
                return Some(ObiSignal {
                    side: OrderSide::Sell,
                    target_venue: VenueId::EXCHANGE_A,
                    symbol,
                    obi_value: obi_b,
                    obi_delta: None,
                    timestamp_ns,
                });
            }
        }

        None
    }

    pub fn current_obi(&self, venue: VenueId) -> Option<f64> {
        match venue {
            VenueId::EXCHANGE_A => self.current_obi_a,
            VenueId::EXCHANGE_B => self.current_obi_b,
            _ => None,
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eal::BookLevel;

    fn make_book(venue: VenueId, bids: Vec<(f64, f64)>, asks: Vec<(f64, f64)>) -> BookUpdate {
        BookUpdate {
            venue,
            symbol: Symbol::new("BTC"),
            bids: bids
                .into_iter()
                .map(|(p, s)| BookLevel { price: p, size: s })
                .collect(),
            asks: asks
                .into_iter()
                .map(|(p, s)| BookLevel { price: p, size: s })
                .collect(),
            exchange_ts_ns: 0,
            local_ts_ns: 0,
        }
    }

    #[test]
    fn test_weighted_obi_calculation() {
        let book = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 20.0), (99.0, 10.0)], // weighted: 20*1 + 10*0.5 = 25
            vec![(101.0, 2.0), (102.0, 3.0)],  // weighted: 2*1 + 3*0.5 = 3.5
        );
        // OBI = (25 - 3.5) / (25 + 3.5) = 21.5 / 28.5 ≈ 0.754
        let obi = book.obi(2); // Simple OBI for comparison
        assert!(obi > 0.0);

        // Weighted should be more extreme (top levels dominate)
        let detector = ObiDivergenceDetector::new(0.7, 0.2, 2, 0.3, 200_000_000);
        let weighted = detector.weighted_obi(&book);
        assert!(
            weighted > obi,
            "Weighted OBI should emphasize top levels more"
        );
    }

    #[test]
    fn test_obi_divergence_with_persistence() {
        // persist_ns = 0 means instant persistence (for testing)
        let mut detector = ObiDivergenceDetector::new(0.7, 0.2, 5, 0.3, 0);

        // A has strong bid imbalance
        let book_a = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 20.0), (99.0, 10.0)],
            vec![(101.0, 2.0), (102.0, 3.0)],
        );
        detector.process_book(&book_a);

        // B is neutral
        let book_b = make_book(
            VenueId::EXCHANGE_B,
            vec![(100.0, 5.0), (99.0, 5.0)],
            vec![(101.0, 5.0), (102.0, 5.0)],
        );
        let signal = detector.process_book(&book_b);

        assert!(signal.is_some());
        let signal = signal.unwrap();
        assert_eq!(signal.side, OrderSide::Buy);
        assert_eq!(signal.target_venue, VenueId::EXCHANGE_B);
    }

    #[test]
    fn test_obi_no_divergence() {
        let mut detector = ObiDivergenceDetector::new(0.7, 0.2, 5, 0.3, 0);

        // Both moderate
        let book_a = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 10.0), (99.0, 5.0)],
            vec![(101.0, 5.0), (102.0, 5.0)],
        );
        detector.process_book(&book_a);

        let book_b = make_book(
            VenueId::EXCHANGE_B,
            vec![(100.0, 8.0), (99.0, 5.0)],
            vec![(101.0, 7.0), (102.0, 5.0)],
        );
        let signal = detector.process_book(&book_b);
        assert!(signal.is_none());
    }

    #[test]
    fn test_persistence_blocks_instant_signals() {
        // persist_ns = 1 second — signal should NOT fire immediately
        let mut detector = ObiDivergenceDetector::new(0.7, 0.2, 5, 0.3, 1_000_000_000);

        let book_a = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 20.0), (99.0, 10.0)],
            vec![(101.0, 2.0), (102.0, 3.0)],
        );
        detector.process_book(&book_a);

        let book_b = make_book(
            VenueId::EXCHANGE_B,
            vec![(100.0, 5.0), (99.0, 5.0)],
            vec![(101.0, 5.0), (102.0, 5.0)],
        );
        let signal = detector.process_book(&book_b);
        assert!(
            signal.is_none(),
            "Persistence filter should block instant signals"
        );
    }
}
