//! OBI divergence detector for order book alpha.
//!
//! Detects when one exchange shows strong bid/ask pressure
//! while the other remains neutral.
//!
//! # Algorithm
//! 1. Calculate OBI for both exchanges
//! 2. Detect when one exchange has strong imbalance (> threshold)
//! 3. Check if other exchange is neutral (< neutral_threshold)
//! 4. Generate signal to trade the neutral exchange

use crate::eal::{BookUpdate, OrderSide, Symbol, VenueId};

/// OBI signal generated by divergence detector
#[derive(Debug, Clone)]
pub struct ObiSignal {
    /// Direction of the trade
    pub side: OrderSide,
    /// Target venue (the neutral one)
    pub target_venue: VenueId,
    /// Symbol to trade
    pub symbol: Symbol,
    /// OBI value on the strong exchange
    pub obi_value: f64,
    /// OBI delta for liquidity shift detection
    pub obi_delta: Option<f64>,
    /// Timestamp when signal was generated
    pub timestamp_ns: u64,
}

/// OBI divergence detector
///
/// Detects when one exchange shows strong bid/ask pressure
/// while the other remains neutral.
pub struct ObiDivergenceDetector {
    /// OBI thresholds
    strong_threshold: f64,
    neutral_threshold: f64,
    /// Depth for OBI calculation
    depth: usize,
    /// Current OBI values
    current_obi_a: Option<f64>,
    current_obi_b: Option<f64>,
    /// Previous OBI for delta detection
    prev_obi_a: Option<f64>,
    /// Spike threshold for liquidity shift detection
    spike_threshold: f64,
}

impl ObiDivergenceDetector {
    /// Create a new OBI divergence detector
    ///
    /// # Arguments
    /// * `strong_threshold` - OBI value considered strong (e.g., 0.7)
    /// * `neutral_threshold` - OBI value considered neutral (e.g., 0.2)
    /// * `depth` - Order book depth for OBI calculation (e.g., 5)
    /// * `spike_threshold` - OBI delta for liquidity shift detection (e.g., 0.3)
    pub fn new(
        strong_threshold: f64,
        neutral_threshold: f64,
        depth: usize,
        spike_threshold: f64,
    ) -> Self {
        Self {
            strong_threshold,
            neutral_threshold,
            depth,
            current_obi_a: None,
            current_obi_b: None,
            prev_obi_a: None,
            spike_threshold,
        }
    }

    /// Process book update and detect divergence
    ///
    /// Returns signal if:
    /// 1. One exchange has strong OBI (> strong_threshold)
    /// 2. Other exchange is neutral (< neutral_threshold)
    pub fn process_book(&mut self, book: &BookUpdate) -> Option<ObiSignal> {
        let venue = book.venue;
        let symbol = book.symbol.clone();
        let timestamp_ns = book.exchange_ts_ns;

        // Calculate OBI
        let obi = book.obi(self.depth);

        // Log OBI for debugging
        tracing::debug!(
            "OBI update: {} | venue={:?} | obi={:.4} | strong_threshold={:.2} | neutral_threshold={:.2}",
            symbol,
            venue,
            obi,
            self.strong_threshold,
            self.neutral_threshold
        );

        // Update current OBI values
        match venue {
            VenueId::EXCHANGE_A => {
                self.prev_obi_a = self.current_obi_a;
                self.current_obi_a = Some(obi);
            }
            VenueId::EXCHANGE_B => {
                self.current_obi_b = Some(obi);
            }
            _ => return None,
        }

        // Check for liquidity shift (delta_obi > spike_threshold)
        let obi_delta = if venue == VenueId::EXCHANGE_A {
            if let (Some(prev), Some(current)) = (self.prev_obi_a, self.current_obi_a) {
                let delta = current - prev;
                if delta.abs() > self.spike_threshold {
                    tracing::info!(
                        "Liquidity shift detected: {} | delta_obi={:.4} | spike_threshold={:.2}",
                        symbol,
                        delta,
                        self.spike_threshold
                    );
                }
                Some(delta)
            } else {
                None
            }
        } else {
            None
        };

        // Check for divergence
        if let (Some(obi_a), Some(obi_b)) = (self.current_obi_a, self.current_obi_b) {
            tracing::debug!(
                "OBI divergence check: {} | obi_a={:.4} | obi_b={:.4} | strong={:.2} | neutral={:.2}",
                symbol,
                obi_a,
                obi_b,
                self.strong_threshold,
                self.neutral_threshold
            );

            // A strong, B neutral → BUY on B
            if obi_a > self.strong_threshold && obi_b.abs() < self.neutral_threshold {
                tracing::info!(
                    "OBI divergence detected: {} | A bullish (OBI={:.4}) | B neutral (OBI={:.4}) → BUY B",
                    symbol,
                    obi_a,
                    obi_b
                );
                return Some(ObiSignal {
                    side: OrderSide::Buy,
                    target_venue: VenueId::EXCHANGE_B,
                    symbol,
                    obi_value: obi_a,
                    obi_delta,
                    timestamp_ns,
                });
            }

            // A negative strong, B neutral → SELL on B
            if obi_a < -self.strong_threshold && obi_b.abs() < self.neutral_threshold {
                tracing::info!(
                    "OBI divergence detected: {} | A bearish (OBI={:.4}) | B neutral (OBI={:.4}) → SELL B",
                    symbol,
                    obi_a,
                    obi_b
                );
                return Some(ObiSignal {
                    side: OrderSide::Sell,
                    target_venue: VenueId::EXCHANGE_B,
                    symbol,
                    obi_value: obi_a,
                    obi_delta,
                    timestamp_ns,
                });
            }

            // B strong, A neutral → BUY on A
            if obi_b > self.strong_threshold && obi_a.abs() < self.neutral_threshold {
                tracing::info!(
                    "OBI divergence detected: {} | B bullish (OBI={:.4}) | A neutral (OBI={:.4}) → BUY A",
                    symbol,
                    obi_b,
                    obi_a
                );
                return Some(ObiSignal {
                    side: OrderSide::Buy,
                    target_venue: VenueId::EXCHANGE_A,
                    symbol,
                    obi_value: obi_b,
                    obi_delta: None,
                    timestamp_ns,
                });
            }

            // B negative strong, A neutral → SELL on A
            if obi_b < -self.strong_threshold && obi_a.abs() < self.neutral_threshold {
                tracing::info!(
                    "OBI divergence detected: {} | B bearish (OBI={:.4}) | A neutral (OBI={:.4}) → SELL A",
                    symbol,
                    obi_b,
                    obi_a
                );
                return Some(ObiSignal {
                    side: OrderSide::Sell,
                    target_venue: VenueId::EXCHANGE_A,
                    symbol,
                    obi_value: obi_b,
                    obi_delta: None,
                    timestamp_ns,
                });
            }
        }

        None
    }

    /// Get current OBI for a venue
    pub fn current_obi(&self, venue: VenueId) -> Option<f64> {
        match venue {
            VenueId::EXCHANGE_A => self.current_obi_a,
            VenueId::EXCHANGE_B => self.current_obi_b,
            _ => None,
        }
    }

    /// Check if OBI has disappeared (no longer strong)
    pub fn is_obi_disappeared(&self, venue: VenueId) -> bool {
        if let Some(obi) = self.current_obi(venue) {
            obi.abs() < self.neutral_threshold
        } else {
            true
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eal::{BookLevel, Symbol};

    fn make_book(venue: VenueId, bids: Vec<(f64, f64)>, asks: Vec<(f64, f64)>) -> BookUpdate {
        BookUpdate {
            venue,
            symbol: Symbol::new("BTC"),
            bids: bids
                .into_iter()
                .map(|(p, s)| BookLevel { price: p, size: s })
                .collect(),
            asks: asks
                .into_iter()
                .map(|(p, s)| BookLevel { price: p, size: s })
                .collect(),
            exchange_ts_ns: 0,
            local_ts_ns: 0,
        }
    }

    #[test]
    fn test_obi_calculation() {
        let book = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 10.0), (99.0, 5.0)],
            vec![(101.0, 2.0), (102.0, 3.0)],
        );
        // OBI = (15 - 5) / (15 + 5) = 0.5
        let obi = book.obi(2);
        assert!((obi - 0.5).abs() < 1e-9);
    }

    #[test]
    fn test_obi_divergence_detector() {
        let mut detector = ObiDivergenceDetector::new(0.7, 0.2, 5, 0.3);

        // A has strong bid imbalance
        let book_a = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 20.0), (99.0, 10.0)],
            vec![(101.0, 2.0), (102.0, 3.0)],
        );
        detector.process_book(&book_a);

        // B is neutral
        let book_b = make_book(
            VenueId::EXCHANGE_B,
            vec![(100.0, 5.0), (99.0, 5.0)],
            vec![(101.0, 5.0), (102.0, 5.0)],
        );
        let signal = detector.process_book(&book_b);

        // Should generate BUY signal on B
        assert!(signal.is_some());
        let signal = signal.unwrap();
        assert_eq!(signal.side, OrderSide::Buy);
        assert_eq!(signal.target_venue, VenueId::EXCHANGE_B);
    }

    #[test]
    fn test_obi_no_divergence() {
        let mut detector = ObiDivergenceDetector::new(0.7, 0.2, 5, 0.3);

        // Both exchanges have moderate imbalance
        let book_a = make_book(
            VenueId::EXCHANGE_A,
            vec![(100.0, 10.0), (99.0, 5.0)],
            vec![(101.0, 5.0), (102.0, 5.0)],
        );
        detector.process_book(&book_a);

        let book_b = make_book(
            VenueId::EXCHANGE_B,
            vec![(100.0, 8.0), (99.0, 5.0)],
            vec![(101.0, 7.0), (102.0, 5.0)],
        );
        let signal = detector.process_book(&book_b);

        // No signal (both moderate)
        assert!(signal.is_none());
    }
}
